services:
  - postgresql
  - mysql
language: php
php:
  - 5.4
  - 5.5
  - 5.6
install:
- phpenv rehash
- composer self-update
- composer require satooshi/php-coveralls:dev-master --no-update --dev
- composer install

before_script:
- psql -c 'create database sqlbuilder;' -U postgres
- mysql -e 'create database sqlbuilder;'

script:
- phpunit -c phpunit.travis-ci.xml

after_success:
- php vendor/bin/coveralls -v

cache:
- vendor
